---
- name: Update apt
  apt: update_cache=yes

- name: Install full nginx
  apt: name={{ item }} state=latest
  with_items:
    - nginx-full

- name: Copy nginx configuration
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx