data:
  image: busybox
  volumes:
    - .:/var/www

php:
  image: "${APP_NAME}:${APP_VERSION}-php56"
  entrypoint: "/bin/bash"
  command: "/entrypoint.sh"
  links:
    - mysql
  volumes_from:
    - data
  environment:
    SYMFONY_ENV: test

mysql:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: ${PROJECT_NAME}
    MYSQL_DATABASE: ${PROJECT_NAME}

nginx:
  image: "${APP_NAME}:${APP_VERSION}-nginx"
  links:
    - php
  volumes_from:
    - data
  environment:
    PROJECT_NAME: ${PROJECT_NAME}
    PROJECT_WEB_DIR: ${PROJECT_WEB_DIR}
    PROJECT_INDEX_FILE: ${PROJECT_INDEX_FILE}
    PROJECT_DEV_INDEX_FILE: ${PROJECT_DEV_INDEX_FILE}



