php:
  entrypoint: "php-fpm"
  command: ""
  environment:
    SYMFONY_ENV: dev

mysql:
  environment:
    MYSQL_DATABASE: ${PROJECT_NAME}
  volumes:
    - ./data:/var/lib/mysql
  ports:
    - "13306:3306"
    - "3306:3306"

nginx:
  image: "${APP_NAME}:${APP_VERSION}-nginx"
  links:
    - php
  volumes_from:
    - data
  environment:
    PROJECT_NAME: ${PROJECT_NAME}
    PROJECT_WEB_DIR: ${PROJECT_WEB_DIR}
    PROJECT_INDEX_FILE: ${PROJECT_INDEX_FILE}
    PROJECT_DEV_INDEX_FILE: ${PROJECT_DEV_INDEX_FILE}
  ports:
    - "8000:80"
