- name: List of files with .dim extension (docker images)
  find: paths="{{projectPath}}/package" patterns="*.dim"
  register: dockerImages

- name: Load docker images
  environment:
    USERID: "{{ userId.stdout }}"
  docker_image:
    timeout: 240
    name: "{{ item.path | basename | replace('.dim', '') }}"
    load_path: "{{ item.path }}"
  with_items: "{{ dockerImages.files }}"