- name: Update nginx configuration
  replace: dest=/etc/nginx/conf.d/default.conf regexp='127.0.0.1:(.*);' replace="127.0.0.1:{{ nextPgsdziuraPort}};" backup=yes
  sudo: yes

- name: Nginx reload
  service: name=nginx state=reloaded
  sudo: yes